[package]
name = "menu_bar_runner3"
version = "0.1.0"
edition = "2021"

[dependencies]
cocoa = "0.26"
objc = "0.2"
core-foundation = "0.10"
libc = "0.2"

# [lints.rust]
# unexpected_cfgs = { level = "warn", check-cfg = ['cfg(cargo-clippy)'] }
